name: CloudFormation Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cfn-lint checkov

      - name: Run cfn-lint
        run: cfn-lint templates/infra.yaml

      - name: Run Checkov
        run: checkov -f templates/infra.yaml
